@extends('layouts.app')
@section('title')
{{ __('HOME') }}
@endsection

@section('content')
<script defer src="{{ asset('assets/js/pagination.js') }}"></script>
<script defer src="{{ asset('assets/js/home.js') }}"></script>
<main class="mt-[75px] pt-[365px] main_container px-[8px] pb-[65px]">
    <div class="header_container container">
        <h1 class="heading xl:!leading-[5rem]">
            Go Multi-Chain with WAX NFT Bridges
        </h1>
        <div class="d-flex gap-3 flex-col lists_container">
            <ul>
                <li class="pt-[2px] xl:pt-[6px]">Lorem ipsum dolor sit amet consectetur</li>
                <li class="pt-[2px] xl:pt-[6px]">Tellus turpis facilisis cursus nullam at quam placerat.</li>
                <li class="pt-[2px] xl:pt-[6px]">Nec odio ante ac feugiat nibh id risus placerat nec.</li>
            </ul>
            <div class="flex gap-[25px]  sm:gap-[22px] pt-[20px] xl:pt-[42px]">
                <a class="mybtnLearnMore" href="#">Learn More</a>
                <a class="mybtnMore" href="#">Learn More</a>
            </div>
        </div>
    </div>
    <div class="container d-flex justify-content-between align-items-center video_container gap-10">
        <div>
            <video controls>
                <source src="/media/cc0-videos/flower.webm" type="video/webm" />
                <source src="/media/cc0-videos/flower.mp4" type="video/mp4" />
            </video>
        </div>
        <div class="d-flex flex-column video_text align-items-end gap-3">
            <h1>
                WAX Earn & Community Hub
            </h1>
            <p>Welcome to our Community Earn Hub! The perfect point to enter the Wax multiverse. Whether you are still new to the WAX ecosystem or interested in completing Tasks or Surveys to earn free WAXP you will find everything you need in one location. Developed for the by active WAX fellows we believe in afair ecosystem and true power to the community we want to offer the highest possible reward for users completing surveys while offering instant withdrawal. We are operating this platform not profit orientated and are distributing profits generated by this Hub directly to all Users who stake our token $Klee on our platform. Enjoy your stay! Kleeblatt.Game</p>
        </div>
    </div>
    <div class="container d-flex flex-column justify-content-center motivation_container">
        <h2>Who We Are & Our Motivation</h2>
        <p>Our Vision at a glance -> Earn crypto by completing Offer/Tasks via various Offerwall Providers with the highest payouts in the industry -> We offer you a new and beginner-friendly way to dive into the wax community and into the crypto space. -> Regardless if you want to earn only crypto or looking for new crypto friends benefit from both worlds. -> Offering additionally our native utility token $KLEE for Hub-related activities you can also passively participate in our success! Who we are We are a group of crypto fanatics who operate under the umbrella of KleeBlatt.</p>
        <p id="secondParagraph">Games with the goal to deliver you earning opportunities where you - the user - receives the highest possible reward for your work and not someone else! Our platform was financed by labs.wax.io as a non-profit project to fill the gap between your interest to explore new thrilling opportunities and regular portals keeping the major cut of profit for your work. Our concept is based on two pillars: -> Your work -> Your Profit, While the specific payout % will depend on the individual offerwall provider and the nature of the tasks, we will need to keep a small share to cover the daily operational costs of the platform and mitigate fraud. We will distribute regularly all profit generated by the Hub that wasn't directly distributed to you back to you with the help of our utility token $KLEE! $KLEE - A WAX Blockchain-based token that will be rewarded additionally to crypto for completing tasks, chatting, playing, and so on. Collecting $KLEE will enable you to participate in our staking pool and receive a regular profit share of additional income from our portal with absolutely no additional effort! Although we haven't launched now, we would like already now to share our spirit and passion with you! That's why we will Airdrop $KLEE to all users who pre-register for the WAX Hub. Ready-Steady-Go, take this first Task and receive your Chance to earn a passive income share from the Hub at launch since you will be one of the few holders.</p>
        <a id="learnMoreLink" href="javascript:void(0);">Learn more</a>
    </div>
    <div class="container cards_container">
        <div id="itemContainer" class="cards">
        </div>
        <div id="pagination" class="pagination">
        </div>
    </div>
    <div class="container d-flex justify-content-between align-items-center mt-[100px] earth_container">
        <div class="d-flex gap-3 flex-col lists_container">
            <h2 class="xl:!leading-[5rem]">Lorem Ipsum Dolor Sit Amet Consectetur Laoreet</h2>
            <ul>
                <li class="pt-[2px] xl:pt-[6px]">Lorem ipsum dolor sit amet consectetur</li>
                <li class="pt-[2px] xl:pt-[6px]">Tellus turpis facilisis cursus nullam at quam placerat.</li>
                <li class="pt-[2px] xl:pt-[6px]">Nec odio ante ac feugiat nibh id risus placerat nec.</li>
            </ul>
            <div class="flex gap-[15px]  sm:gap-[22px] pt-[20px] xl:pt-[42px]">
                <a class="mybtnLearnMore" href="#">Learn More</a>
                <a class="mybtnMore" href="#">Learn More</a>
            </div>
        </div>
        <div>
            <img src="{{ asset('assets/images/earth.png') }}" alt="earth" />
        </div>
    </div>
</main>
@endsection